### ISSUE TITLE
Behaveior Differences Compared to Project Run in Codea

### ISSUE THREAD

**Issue by elian** [lowne/xCodea#1]
Hi,

During testing of xCodea with one of my projects, I observd the following differences in behaviour of xCodea compared to the project run in Codea:

Note: I am using LDT for project edit.

1) If a 'parameter.number' variable is changed in running code (not through the GUI), the GUI doesen't follow the chanched value as it happens in standard Codea.

2) Using the 'SaveImage("Project:Icon", myicon)' to set the icin of the Project actually is setting 'xCodea' Project's icon, not the tested Project's one.

3) (Off-topic) At first sync of project files by xCodea server, resulting in copying from iPad to Mac under LDT project, all .lua files of the project are owned by 'system' account w/read/write permission and my account is missing from account permission list.

Thus, after modifying some bits in LDT, when I want to save the modified .lua file, I get the error 'Permission denied'. A turnaround for this, is to use the 'chown -R.' command to changing ownership of all the project files.

4) (Off-topic) After a lot of try-and-error (I am not a skiled OS X user/programmer), I finaly installed all (I hope) the necessary Xcode and python command line tools and site-packages, including the 'rumps' package, necessary to make an xCode py2app. The app is functonal till a point, generating an error imediatly after poping up the request for allowance to inbound connections to xCodea server.

Here is a Console log for this:

27/03/14 05:24:56,858 com.apple.launchd.peruser.501[228]: (com.marklowne.xCodea.82928[1143]) Exited with code: 255
27/03/14 05:25:30,652 xCodea[1146]: Traceback (most recent call last):
27/03/14 05:25:30,653 xCodea[1146]:   File "/Users/elianepstain/LDTProjects/CodeaProjects/dist/xCodea.app/Contents/Resources/**boot**.py", line 341, in <module>
27/03/14 05:25:30,653 xCodea[1146]:     _run()
27/03/14 05:25:30,653 xCodea[1146]:   File "/Users/elianepstain/LDTProjects/CodeaProjects/dist/xCodea.app/Contents/Resources/__boot__.py", line 336, in _run
27/03/14 05:25:30,653 xCodea[1146]:     exec(compile(source, path, 'exec'), globals(), globals())
27/03/14 05:25:30,653 xCodea[1146]:   File "/Users/elianepstain/LDTProjects/CodeaProjects/dist/xCodea.app/Contents/Resources/xCodea.py", line 199, in <module>
27/03/14 05:25:30,654 xCodea[1146]:     rumps.MenuItem('Show log',callback=show_log),
27/03/14 05:25:30,654 xCodea[1146]:   File "/Users/elianepstain/LDTProjects/CodeaProjects/dist/xCodea.app/Contents/Resources/lib/python2.7/rumps/rumps.py", line 340, in __init__
27/03/14 05:25:30,654 xCodea[1146]:     self.set_callback(callback, key)
27/03/14 05:25:30,654 xCodea[1146]:   File "/Users/elianepstain/LDTProjects/CodeaProjects/dist/xCodea.app/Contents/Resources/lib/python2.7/rumps/rumps.py", line 396, in set_callback
27/03/14 05:25:30,654 xCodea[1146]:     self._menuitem.setTarget_(type(self))
27/03/14 05:25:30,654 xCodea[1146]: ValueError: NSInvalidArgumentException - Class OC_PythonObject: no such selector: methodForSelector:
27/03/14 05:25:30,720 xCodea[1146]: xCodea Error
27/03/14 05:25:30,720 xCodea[1146]: 2014-03-27 05:25:30.718 xCodea[1146:707] xCodea Error
27/03/14 05:26:01,093 com.apple.launchd.peruser.501[228]: (com.marklowne.xCodea.82928[1146]) Exited with code: 255

I realy apreciate your efforts in developing xCodea, an excelent, most helpful project.

Thanks,
Elian Epstan

**Comment by lowne** [comment]
Thanks for the extensive feedback! Would you mind copy-pasting into 4 separate issues? (I'd do it myself, but then I have no idea how to notify you of updates)

**Comment by elian** [comment]
OK. Closing this issue.
