### ISSUE TITLE
Ownership Issue on Files at First Sync of Project from iPad to Server

### ISSUE THREAD

**Issue by elian** [lowne/xCodea#4]
Hi,

During testing of xCodea with one of my projects, I observd the following differences in behaviour of xCodea compared to the project run in Codea:

Note: I am using LDT for project edit on OS X 10.9.2 and xCodea runs on an iPad2.

3) At first sync of project files by xCodea server, resulting in copying from iPad to Mac under LDT project, all .lua files of the project are owned by 'system' account w/read/write permission and my account is missing from account permission list.

Thus, after modifying some bits in LDT, when I want to save the modified .lua file, I get the error 'Permission denied'. A turnaround for this, is to use the 'chown -R.' command to changing ownership of all the project files.

Thanks,
Elian Epstan

**Comment by lowne** [comment]
This is absolutely weird. AFAIK any process (and the files it creates) runs from the account that launched it; so unless you ran the server with sudo, I cannot explain it. Can you share more details on how you launched the server? Or even better, can you detail how to systematically reproduce the issue?

**Comment by elian** [comment]
Hi,

Looks like you were right. I double-checked how I started the server and it looks like I changed through sudo the account. Now I start it normally through cli or xCodea.app and everything is ok (the first synced .lua files are owned by my account w/read/write permissions).

Thans,
Elian
